###
GET https://api-juanmcell-production.up.railway.app/venta HTTP/1.1

###
POST https://api-juanmcell-production.up.railway.app/venta HTTP/1.1
Content-Type: application/json

{
    "ganancia": 0,
    "caja": 0,
    "id": 1

}

###
DELETE https://api-juanmcell-production.up.railway.app/venta/2 HTTP/1.1

###
PUT https://api-juanmcell-production.up.railway.app/venta/1 HTTP/1.1
Content-Type: application/json

{
     "nombre": "cable tipo c",
    "cantidad": 9,
    "precio": 10000
}