###
GET hhttp://api-juanmcell-production.up.railway.app/api HTTP/1.1

###
POST http://api-juanmcell-production.up.railway.app/api HTTP/1.1
Content-Type: application/json

{
    "nombre": "oneplus",
    "cantidad": 8,
    "precio": 120000,
    "id": 3

}

###
DELETE http://api-juanmcell-production.up.railway.app/api/2 HTTP/1.1

###
PUT http://api-juanmcell-production.up.railway.app/api/1 HTTP/1.1
Content-Type: application/json

{
     "nombre": "cable tipo c",
    "cantidad": 9,
    "precio": 10000
}