###
GET http://localhost:9001/display HTTP/1.1

###
POST http://localhost:9001/display HTTP/1.1
Content-Type: application/json

{
    "referencia": "oneplus",
    "marca":"original",
    "tipo":"amoled",
    "cantidad": 8,
    "precio": 120000,
    "costoProveedor":140000, 
    "id": 2

}

###
DELETE http://localhost:9001/display/2 HTTP/1.1

###
PUT http://localhost:9001/display/1 HTTP/1.1
Content-Type: application/json

{
     "nombre": "cable tipo c",
    "cantidad": 9,
    "precio": 10000
}